### ISSUE TITLE
input [32 x 64 x 64] and target [32 x 17 x 64 x 64] shapes do not match when training indian pines and calculating MSEloss 

### ISSUE THREAD

**Issue by apri0426** [B-Manifold/pytorch_fnet_UwUnet#1]
I am training test_indian_pines script and the problem is as the title.
could anyone solve the problem?

`Using existing train/test split.

Model instianted from: fnet_nn_UwU

fnet_nn_UwU | {} | iter: 0

0%|          | 0/6 [00:00<?, ?it/s]^Mbuffering images:   0%|          | 0/6 [00:00<?, ?it/s]
buffering images:  17%|█▋        | 1/6 [00:02<00:13,  2.77s/it]
buffering images:  17%|█▋        | 1/6 [00:02<00:13,  2.77s/it]
buffering images:  33%|███▎      | 2/6 [00:03<00:06,  1.55s/it]
buffering images:  33%|███▎      | 2/6 [00:03<00:06,  1.56s/it]
buffering images:  50%|█████     | 3/6 [00:03<00:03,  1.16s/it]
buffering images:  50%|█████     | 3/6 [00:03<00:03,  1.16s/it]
buffering images:  67%|██████▋   | 4/6 [00:03<00:01,  1.09it/s]
buffering images:  67%|██████▋   | 4/6 [00:03<00:01,  1.09it/s]
buffering images:  83%|████████▎ | 5/6 [00:04<00:00,  1.17it/s]
buffering images:  83%|████████▎ | 5/6 [00:04<00:00,  1.17it/s]
buffering images: 100%|██████████| 6/6 [00:04<00:00,  1.27it/s]
<fnet.data.tiffdataset.TiffDataset object at 0x2acb5b7ded68>
0
1
2
3
4
5
Traceback (most recent call last):
  File "train_model.py", line 160, in <module>
    main()
  File "train_model.py", line 127, in main
    loss_batch = model.do_train_iter(signal, target)
  File "/project/zmchai/pytorch_fnet_UwUnet-1.0.0/fnet/fnet_model.py", line 95, in do_train_iter
    loss = self.criterion(output, target)
  File "/home/zmchai/project/anaconda3/envs/fnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zmchai/project/anaconda3/envs/fnet/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 372, in forward
    return F.mse_loss(input, target, size_average=self.size_average, reduce=self.reduce)
  File "/home/zmchai/project/anaconda3/envs/fnet/lib/python3.6/site-packages/torch/nn/functional.py", line 1569, in mse_loss
    input, target, size_average, reduce)
  File "/home/zmchai/project/anaconda3/envs/fnet/lib/python3.6/site-packages/torch/nn/functional.py", line 1537, in _pointwise_loss
    return lambd_optimized(input, target, size_average, reduce)
RuntimeError: input and target shapes do not match: input [32 x 64 x 64], target [32 x 17 x 64 x 64] at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THCUNN/generic/MSECriterion.cu:15
`

**Comment by B-Manifold** [comment]
Hi apri,

I think I know what the issue is. It's lines 34-38 in /fnet/nn_modules/fnet_nn_UwU.py. It's probably currently running the line for if the final channel size is supposed to be 1 (line 35 as currently written). If you comment out that line and uncomment line 38, that should fix the issue you're seeing. Feel free to reopen this issue if this doesn't work!

Best
