### ISSUE TITLE
 How can we train the MSI dataset?

### ISSUE THREAD

**Issue by banxianerr** [B-Manifold/pytorch_fnet_UwUnet#2]
Thank you very much for your contribution. I learned a lot from your code,  I have some questions, if I want to train this model in the MSI dataset, what should I do?

**Comment by B-Manifold** [comment]
Assuming you mean the same MSI dataset we demonstrated:
You can download the data from the link in the Readme. You'll also need an MSI viewing software. We used DatacubeExplorer in the paper. You can find all of the exact details for prepping the MSI dataset in the "Training parameters, data preparation and hardware" section of our paper! (https://www.nature.com/articles/s42256-021-00309-y)

If you mean on your own MSI dataset:
You should be able to follow the same general instructions as what we do in the paper. Though you may want to consider different m/z ranges and/or m/z resolutions depending on the relevant species in your sample.

Feel free to email me at bmanifol@uw.edu if you need more help!
